spring:
  profiles:
    active: native
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: clsspath:/configurations
server:
  port: 8888