services:
  postgres:
    container_name: ms_postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - microservices_net

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: pass
    networks:
      - microservices_net
    ports:
      - "5050:80"

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongo
    volumes:
      - "mongo:/data"

  mongooexpress:
    container_name: ms_mongo_express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microservices_net:
    driver: bridge

volumes:
  postgres:
  mongo: